sudo: false
language: objective-c
cache: cocoapods
xcode_workspace: LocationManagerExample/LocationManagerExample.xcworkspace
before_install:
  - gem install slather --no-ri --no-rdoc
  - pod install --project-directory=LocationManagerExample

after_success: slather
