sudo: false
language: objective-c
cache: cocoapods
xcode_workspace: LocationManagerExample/LocationManagerExample.xcworkspace
xcode_scheme: LocationManagerExample
podfile: LocationManagerExample/Podfile
after_success: slather
